
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: bankappdb
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  bankapp:
    image: $IMAGE_NAME:$IMAGE_TAG
    # build:
      # context: .
      # dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    depends_on:
      - mysql

volumes:
  mysqldata:

