kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    image: kindest/node:v1.34.0
    extraPortMappings:
      - containerPort: 30007
        hostPort: 8000
      - containerPort: 30008
        hostPort: 8001
      - containerPort: 30009
        hostPort: 8002

  - role: worker
    image: kindest/node:v1.34.0
      # - role: worker
      # image: kindest/node:v1.34.0

# kind create cluster --config cluster.yaml --name kind-cluster
# kind delete cluster --name kind-cluster
# kind get clusters
