name: Main pipeline

on:
  workflow_dispatch:


jobs:
  secrets-scan:
    uses: ./.github/workflows/01-secrets-scan.yaml

  code-scan:
    uses: ./.github/workflows/02-code-scan.yaml

  build-scan:
    needs: ["secrets-scan", "code-scan"]
    uses: ./.github/workflows/03-build-scan.yaml
  


