name: 00 Main pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - start


jobs:
  secrets-scan:
    uses: ./.github/workflows/01-secrets-scan.yaml

  code-scan:
    uses: ./.github/workflows/02-code-scan.yaml

  build-scan:
    needs: ["secrets-scan", "code-scan"]
    uses: ./.github/workflows/03-build-scan.yaml
    secrets: inherit

# secrets inherit as we are using reusable workflow so they should able to get secrets 

  deploy-ec2:
    needs: [build-scan]
    uses: ./.github/workflows/04-deploy.yaml
    secrets: inherit
  


