name: 02 Code scan and quality check

on:
  workflow_call:
    
jobs:
  code-scan:
    runs-on: ubuntu-latest 

    strategy:
      fail-fast: true
      matrix:
        language: ["java"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Codeql init
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}

      - name: Build code
        run: mvn clean package -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
      
      - name: debug
        run: |
          ls 
          ls target/*
        
