name: 04 Deploy to ec2

on:
  workflow_call:
    
  workflow_dispatch:

env:  
  IMAGE_TAG: ${{github.sha}}
  IMAGE_NAME: "${{vars.DOCKERHUB_USERNAME}}/bankapp"

jobs:
  
  check-dependency:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: SSH and check docker
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami

            if docker --version >/dev/null 2>&1; then
              echo "Docker is present"
            else
              echo "Docker is not installed"
              sudo apt-get update
              sudo apt-get install docker.io -y 
              sudo apt-get install docker-compose-plugin -y

              DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
              mkdir -p $DOCKER_CONFIG/cli-plugins
              curl -SL https://github.com/docker/compose/releases/download/v5.0.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
              chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

              sudo usermod -aG docker $USER
              sudo newgrp docker
            fi

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: check-dependency
    environment: prod

    steps:
      - name: Get files on runner
        uses: actions/checkout@v6

      - name: copy compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yaml"
          target: "$HOME"

      - name: ssh and deploy 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export IMAGE_NAME=${{env.IMAGE_NAME}}
            export IMAGE_TAG=${{env.IMAGE_TAG}}
            if ! docker info | grep -q "${{ secrets.DOCKERHUB_USERNAME }}"; then
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            fi
            cd $HOME

            docker compose down || true
            
            docker compose up -d --pull always
            
            